name: Build and save my Docker image to a regitry

on:
  push:
    branches:
      - main # Déclenchement lorsque le code est poussé sur main

env:
  REG_NAME: "acrinfofd22210.azurecr.io" # Nom du registy
  IMAGE_NAME: "todo-backend-vorlet-1.0" # Nom de votre image

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: login registry
        uses: docker/login-action@v3
        with:
          registry: ${{env.REG_NAME }}
          username: ${{secrets.REGISTRY_USERNAME}}
          password: ${{secrets.REGISTRY_PASSWORD}}

      - name: Build docker image
        run: |
          docker build -t $REG_NAME/$IMAGE_NAME:${{ github.sha }} ./src/backend

      - name: Push docker image
        run: |
          docker push $REG_NAME/$IMAGE_NAME:${{ github.sha }}
